"""Stable public API for the small-gpt training system."""

from .checkpoint import (
    CHECKPOINT_FORMAT_NAME,
    CHECKPOINT_SCHEMA_VERSION,
    RNG_STATE_SCHEMA_VERSION,
    CheckpointCompatibilityError,
    CheckpointError,
    CheckpointIdentity,
    CheckpointIdentityError,
    CheckpointLoadError,
    CheckpointRecord,
    CheckpointSaveError,
    LoadedCheckpoint,
    RngStateError,
    build_checkpoint_identity,
    capture_rng_state,
    load_checkpoint,
    load_model_checkpoint,
    restore_rng_state,
    save_checkpoint,
)
from .config import (
    ResolvedTrainingPlan,
    TrainingConfig,
    TrainingConfigError,
    training_field_names,
)
from .data_stream import (
    DataStreamError,
    OffsetSampler,
    TrainingDataStream,
    ValidationDataStream,
)
from .evaluation import (
    EvaluationError,
    EvaluationMetrics,
    evaluate_model,
)
from .loop import (
    TrainingLoopError,
    TrainingLoopResult,
    run_training_loop,
)
from .optimizer import (
    OptimizerConfigError,
    OptimizerParameterGroups,
    build_optimizer,
    partition_parameters,
)
from .precision import (
    DeviceResolutionError,
    PrecisionConfigError,
    PrecisionPolicy,
    resolve_device,
)
from .scheduler import (
    SchedulerConfigError,
    SchedulerStateError,
    WarmupCosineScheduler,
    build_scheduler,
    warmup_cosine_lr,
)
from .run_logging import (
    JsonlMetricLogger,
    MetricLoggingError,
    RunDirectoryError,
    RunPaths,
    initialize_run_directory,
    open_existing_run_directory,
    read_metric_events,
    validate_run_id,
)
from .state import (
    TRAINER_STATE_SCHEMA_VERSION,
    TrainerState,
    TrainerStateError,
)
from .trainer import (
    BatchContractError,
    NonFiniteTrainingError,
    Trainer,
    TrainingStepError,
    UpdateMetrics,
)

__all__ = [
    "BatchContractError",
    "CHECKPOINT_FORMAT_NAME",
    "CHECKPOINT_SCHEMA_VERSION",
    "CheckpointCompatibilityError",
    "CheckpointError",
    "CheckpointIdentity",
    "CheckpointIdentityError",
    "CheckpointLoadError",
    "CheckpointRecord",
    "CheckpointSaveError",
    "DataStreamError",
    "DeviceResolutionError",
    "EvaluationError",
    "EvaluationMetrics",
    "JsonlMetricLogger",
    "LoadedCheckpoint",
    "MetricLoggingError",
    "NonFiniteTrainingError",
    "OffsetSampler",
    "OptimizerConfigError",
    "OptimizerParameterGroups",
    "PrecisionConfigError",
    "PrecisionPolicy",
    "ResolvedTrainingPlan",
    "RNG_STATE_SCHEMA_VERSION",
    "RunDirectoryError",
    "RunPaths",
    "RngStateError",
    "SchedulerConfigError",
    "SchedulerStateError",
    "TRAINER_STATE_SCHEMA_VERSION",
    "Trainer",
    "TrainerState",
    "TrainerStateError",
    "TrainingConfig",
    "TrainingConfigError",
    "TrainingDataStream",
    "TrainingLoopError",
    "TrainingLoopResult",
    "TrainingStepError",
    "UpdateMetrics",
    "ValidationDataStream",
    "WarmupCosineScheduler",
    "build_optimizer",
    "build_scheduler",
    "build_checkpoint_identity",
    "capture_rng_state",
    "evaluate_model",
    "initialize_run_directory",
    "load_checkpoint",
    "load_model_checkpoint",
    "open_existing_run_directory",
    "partition_parameters",
    "read_metric_events",
    "resolve_device",
    "restore_rng_state",
    "run_training_loop",
    "save_checkpoint",
    "training_field_names",
    "validate_run_id",
    "warmup_cosine_lr",
]
